### ISSUE TITLE
Help a newbie

### ISSUE THREAD

**Issue by SAUUU** [allendema/SnapScrap.py#1]
Traceback (most recent call last):
  File "/root/SnapScrap.py-main/SnapScrap.py", line 154, in <module>
    main()
  File "/root/SnapScrap.py-main/SnapScrap.py", line 145, in main
    download_media()
  File "/root/SnapScrap.py-main/SnapScrap.py", line 110, in download_media
    r = requests.get(file_url, stream=True, headers=headers)
NameError: name 'headers' is not defined

**Comment by allendema** [comment]
It was a problem accesing headers variable.

Updated it.
